name: Run RST tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set Up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
        # Install dependencies using pipenv
      - name: Install pipenv
        run: apt install pipenv
      - name: Install pipenv dependencies
        run: |
          pipenv install
          pipenv shell
        # Run the tests using pytest
      - name: Run tests
        run: pytest tests/*
